FROM #TAG

RUN apt update && apt install build-essential libncurses-dev linux-headers-#KERNEL -y
RUN git clone https://github.com/AnthraX1/Reptile.git
COPY ../configs/defconfig /Reptile/.config
RUN make && make gen_installer


